### ISSUE TITLE
Add-on not installed when profile is specified

### ISSUE THREAD

**Issue by jryans** [mozilla/jpm#156]
Node: 0.10.31
JPM: 0.0.13

I tested this against a sample addon which I created from "jpm init" and picking the defaults for all options.

If I try to run while giving a profile:
```
JPM_FIREFOX_BINARY=/Applications/FirefoxNightly.app jpm run -v --binary-args -foreground -p development
```
the add-on is not installed when Firefox launches. It does not appear in the add-on manager at all. I did not see any errors in the Browser Console.

If I drop the profile argument:
```
JPM_FIREFOX_BINARY=/Applications/FirefoxNightly.app jpm run -v --binary-args -foreground
```
the add-on is correctly installed.

**Comment by erikvold** [comment]
@jryans mind giving this another try?

**Comment by jryans** [comment]
Cool, it seems to work as I would expect now! Thanks! :D
