### ISSUE TITLE
jpm init default name should be in lower case

### ISSUE THREAD

**Issue by anaran** [mozilla/jpm#160]
Using latest

```
*   commit ed278ae (HEAD, master)
|\  Merge: 0bc72ea d0f0003
| | Author: Erik Vold <evold@mozilla.com>
| | Date:   Tue Aug 26 07:34:27 2014 -0700
| |
| |     Merge branch 'master' of github.com:mozilla/jpm into 147 r=@erikvold
| |
| |     Conflicts:
| |             package.json
| |
| *   commit d0f0003
```

set up with

```
cd jpm
npm install
npm link
```

# Prompting Issues

`jpm init` defaults and generated files seem inconsistent:

`name: (IssuePilot)`
- [ ] It should be `issuepilot`, which is what ends up in the generated `package.json`

No id is prompted for, nor generated
- [ ] It should prompt for an id
- [ ] It should offer a default for an id value

# Generation Issues

Generated file `test/test-index.js` contains `var main = require("../");`
- [ ] It should explicitly require `../index.js` with `var main = require("../index");`

I'll update above list from your feedback.

# Generated package.json

```
{
  "title": "Issue Pilot",
  "name": "issuepilot",
  "version": "0.0.0",
  "description": "Report issues for supported projects, based on content extracted from webpage.",
  "main": "index.js",
  "author": "anaran",
  "engines": {
    "firefox": ">=33.0a1",
    "fennec": ">=33.0a1"
  },
  "license": "MIT"
}
```

**Comment by erikvold** [comment]
the `id` is not required, so I don't think prompting for an `id` is a good idea, nor providing a default one.  We are actually trying to encourage npm style `package.json` files.

**Comment by erikvold** [comment]
> It should explicitly require ../index.js with var main = require("../index");

Ya I don't agree with this either, I think the way it is now helps people learn if they don't already know how `../` works.

**Comment by erikvold** [comment]
> It should be issuepilot, which is what ends up in the generated package.json

This looks like an issue, so I will leave this open for that reason.

**Comment by erikvold** [comment]
>  It should offer a default for an id value
the name is used to generate an id by default so this is resolved.
