### ISSUE TITLE
Default Firefox path for jpm doesn't work on Ubuntu

### ISSUE THREAD

**Issue by ericschultz** [mozilla/jpm#178]
I'm running Ubuntu 14.04 with Firefox 34.0a2 (2014-09-22)
----
While trying to run 'jpm test' on a new add-in created with 'jpm init,' I receive the following output (minus formatting and JPM header at the beginning):

```bash
Running test on Desktop
The `version` entry must be specified, and it should follow semantic
versioning rules.

http://semver.org

XPI created at /tmp/jid1-5RUIvXqVSOhnMw@jetpack.xpi (13605ms)
Error: spawn ENOENT
[object Object]
```
I couldn't figure out what was going on at first. I eventually ran 'jpm test -v' and noticed something: the path being used by jpm test was /usr/lib64/firefox. /usr/lib64/firefox is not where the Firefox binary is on Ubuntu; instead it's in /usr/bin/firefox (might be symlinked elsewhere too).

Ideally jpm should figure out where the firefox installation is on the system and use that for tests. How we could handle cases where there are multiple versions installed is not entirely clear to me.

As a mitigation, it would be nice if jpm checked for the firefox installation and provided a useful error message so people would know what the problem actually is. I just stumbled on this by running jpm test -v but that shouldn't be necessary.

**Comment by chocolateboy** [comment]
`/usr/bin/firefox` isn't a binary:

```sh
file /usr/bin/firefox
/usr/bin/firefox: symbolic link to `../lib/firefox/firefox.sh'
```

The path resolution code in `normalizeBinary` (`lib/utils.js`) looks like it's meant to probe (e.g.):

* "firefox on linux": "/usr/lib/firefox"
* "firefox on linux(64)": "/usr/lib64/firefox"

but instead probes:

* "firefox on linux(64)": "/usr/lib64/firefox"
* "firefox on linux(64)(64)": undefined

But even the "correct" paths don't work: they're directories. On my system (Ubuntu 14.04), the binary is in: `/usr/lib/firefox/firefox`. The only reference to any of the other paths I can find (@shosca) is: [`/usr/lib/firefox-nightly/firefox-nightly`](https://github.com/shosca/-pkgbuild-mozilla-git/blob/master/firefox-nightly/firefox-nightly.desktop).

Note: `arch` is still being appended to `platform` on Windows even though it isn't used (the lookup table is no longer being used for Windows paths). Someone else can clean that up :-)

**Comment by chocolateboy** [comment]
I didn't spot the [failing tests](https://travis-ci.org/mozilla/jpm/jobs/45609360) because I have so many failing (in master) I assumed my environment isn't set up correctly to run them and I didn't fancy trying to build/install Firefox from source.

Not sure how to fix the tests and and get them passing on Ubuntu since they seem to expect the x86_64 binaries to be in /usr/lib64/firefox/ :-/

**Comment by erikvold** [comment]
I've moved this code to [erikvold/fx-runner](https://github.com/erikvold/fx-runner) so that it can be used in other projects, or as a stand alone cli, and so that it is easier to make changes without affecting jpm.
