### ISSUE TITLE
Hanging on running/building large add-on

### ISSUE THREAD

**Issue by brettz9** [mozilla/jpm#222]
Hi,

I'm trying to compile what I know is quite a [large add-on](https://github.com/brettz9/webappfind) (~226 MB), but whereas cfx works immediately, jpm keeps running and hasn't yet finished. Can this be fixed?

Thanks,
Brett

**Comment by erikvold** [comment]
@brettz9 you can use `.jpmignore` now, does that help?

**Comment by brettz9** [comment]
Sounds cool, thanks!
