### ISSUE TITLE
jpm xpi keeps recursively packaging the last build of the add-on into the new build

### ISSUE THREAD

**Issue by canuckistani** [mozilla/jpm#226]
I think because of change b3e1b7e5c0e6d59ef27f266642b5418f8a5e0655 - what happens is:

1. run jpm xpi
2. test, see a problem, fix it
3. run jpm xpi again, new xpi contains previous xpi.

Maybe we should track the last build and delete it before creating the new one? Are we using a temp directory?

**Comment by erikvold** [comment]
Closed by bb71643
