### ISSUE TITLE
jpm doesn't give a useful error when nonexistent modules are require'd

### ISSUE THREAD

**Issue by wbamberg** [mozilla/jpm#232]
An add-on like this:

    var blah = require("./blah.js");
    console.log("running");

...will not work if ./blah.js does not exist. But jpm will log output like this:

JPM info console.error: my-addon: 
JPM info console.error: my-addon:

...which doesn't give me any indication of what might be wrong.

jpm 0.0.21, Firefox 35.

**Comment by JohnLZeller** [comment]
+1

**Comment by erikvold** [comment]
I think we could use jshell and the Reflect global for this https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Shell_global_objects

There might be something on npm to help use parse js too.

**Comment by erikvold** [comment]
ah this was a runtime issue, and it is fixed by #112
