### ISSUE TITLE
jpm test should check devDependencies 

### ISSUE THREAD

**Issue by fflorent** [mozilla/jpm#236]
**STR:**
1. Do a fresh clone of the Firebug.next repository (anew and elsewhere if you already have it on your disk):
`git clone https://github.com/firebug/firebug.next.git`
2. Go in the firebug.next repository:
`cd firebug.next`
3. run `jpm test -b <path to firefox bin> -v`

**Actual result:**
The test are not run because of missing a dependency (you should see this error):
````
Date: Fri Jan 02 2015 14:15:02 GMT+0100 (CET)
Full Message: Module `addon-httpd` is not found at resource://gre/modules/commonjs/addon-httpd.js
Full Stack: @resource://firebug-at-software-dot-joehewitt-dot-com/test/httpd.js:6:30
@resource://firebug-at-software-dot-joehewitt-dot-com/test/common.js:8:25
@resource://firebug-at-software-dot-joehewitt-dot-com/test/toolbox.js:10:25
@resource://firebug-at-software-dot-joehewitt-dot-com/test/test-command-editor.js:9:33
findTests/</getNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:164:25
findTests/</<.getNext@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:197:32
runNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:499:14
startMany@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:513:12
findAndRunTests/<@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:28:1
Handler.prototype.process@resource://gre/modules/Promise-backend.js:870:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:749:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:691:37
" {file: "resource://firebug-at-software-dot-joehewitt-dot-com/test/httpd.js" line: 6 column: 0 source: "6"}]
````

Note: if you look at the `package.json` file, addon-httpd is listed in `devDependencies`.

**Expected result**
Before running the tests, `jpm test` should check that the dependencies listed in `devDependencies` are installed.

Florent

**Comment by erikvold** [comment]
you have to run `npm install` on your `firebug.next` repo

**Comment by fflorent** [comment]
Actually, I know.
The expected result (if possible) is the following: 
> Before running the tests, jpm test should check that the dependencies listed in devDependencies are installed.

That is after this error that a new contributor has encountered that I opened the issue.

Florent

**Comment by erikvold** [comment]
I see what the request was for here now, a check that devDependencies is fulfilled.

I still think that we should leave this bug closed because for one `npm test` does not do this, and secondly I think devs should be wiring `npm test` to use `jpm test`, in which case this bug should be filed for `npm`.

**Comment by fflorent** [comment]
Well, I still think that it would be worthy to have it:
1. Users (occasional ones, say) may not be aware that it is tight in with `npm test`
2. It doesn't prevent to do better than `npm`, right? =)

If `jpm test` actually use `npm test`, so OK, I can fill an issue to them.

Florent
