### ISSUE TITLE
Addon rejected because of bootstrap.js

### ISSUE THREAD

**Issue by fczbkk** [mozilla/jpm#249]
I have generated XPI of [my addon](https://github.com/fczbkk/github-issues-extension) using JPM and tried to submit it to AMO. It was rejected by reviewer Leszek Życzkowski, because:

> bootstrap.js is not recognized as part of SDK package. Please repack your add-on.

The file was added by JPM and I did not modify it in any way.

What does it mean? Are addons built by JPM not eligible for AMO? Or is this some bug in JPM? Please advise.

**Comment by erikvold** [comment]
This is [bug 1130795](https://bugzilla.mozilla.org/show_bug.cgi?id=1130795)
