### ISSUE TITLE
Update package.json docs to mention all supported fields

### ISSUE THREAD

**Issue by jryans** [mozilla/jpm#250]
The MDN [package.json docs][1] appear to be missing some fields, such as `updateURL` and `updateKey`.

We should make sure all supported fields are described there.

[1]: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

**Comment by erikvold** [comment]
hmm not sure that supporting `updateURL` and `updateKey` makes sense any more.

**Comment by erikvold** [comment]
we should make a sdk documentation bug for @wbamberg to update that page.

**Comment by erikvold** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1133041
