### ISSUE TITLE
/usr/bin/env: node: No such file or directory - Ubuntu

### ISSUE THREAD

**Issue by ghde** [mozilla/jpm#260]
On ubuntu linux systems the node package is called nodejs rather than node [1].
This is why by default jpm is not working on ubuntu.
```
root@server:~$ jpm -V
/usr/bin/env: node: No such file or directory
```

To fix the error the jpm shell script should have
```
#!/usr/bin/env nodejs
```
instead of
```
#!/usr/bin/env node
```
for ubuntu systems or of course any other logic to be working out of the box on ubuntu systems.

[1] https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by erikvold** [comment]
you should see http://stackoverflow.com/questions/20886217/browserify-error-usr-bin-env-node-no-such-file-or-directory
