### ISSUE TITLE
eliminate wget requirement

### ISSUE THREAD

**Issue by inbasic** [mozilla/jpm#273]
By using nodejs there is no need to have wget in order for the JPM to send the generated XPI to Extension Auto-Installer.

Check my implementation,
https://github.com/inbasic/ignotifier/blob/master/compile/install.js#L44-L70

**Comment by erikvold** [comment]
@inbasic looks cool! could you make a pull request?

**Comment by inbasic** [comment]
done

**Comment by erikvold** [comment]
thanks!
