### ISSUE TITLE
Support Fennec

### ISSUE THREAD

**Issue by jsantell** [mozilla/jpm#4]

**Comment by ronald05arias** [comment]
Any updates on this @jsantell ?

**Comment by jsantell** [comment]
Not sure about fennec support, @erikvold might have a better idea

**Comment by ronald05arias** [comment]
@erikvold @jsantell How complex/realistic it's to implement this? Can you point me in the direction to give a hand?

**Comment by erikvold** [comment]
Use [`jpm-mobile`](https://www.npmjs.com/package/jpm-mobile)

* https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm-mobile
* https://www.npmjs.com/package/jpm-mobile
* https://github.com/erikvold/jpm-mobile
