### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by jsantell** [mozilla/jpm#92]
Currently errors thrown in Firefox/Addons go to stdout in the process spawned by jpm, so we'll have to do some clever parsing to determine if it's an error, as this should be logged regardless of verbosity level set.

**Comment by erikvold** [comment]
ffed64313ed90abbf8613df864d82def54091980 should resolve this, reopen if it's still an issue.

**Comment by canuckistani** [comment]
Confirmed, fixed!
